src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $subText = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['name'])]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $imageFilename = null;

    #[ORM\Column(type: Types::JSON)]
    private array $ingredients = [];

    #[ORM\Column(type: Types::JSON)]
    private array $instructions = [];

    #[ORM\Column]
    private ?int $totalTime = null;

    #[ORM\Column(length: 255)]
    private ?string $sourceUrl = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSubText(): ?string
    {
        return $this->subText;
    }

    public function setSubText(string $subText): self
    {
        $this->subText = $subText;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function getImageUrl(): string
    {
        return 'uploads/recipes/' . $this->getImageFilename();
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getIngredients(): array
    {
        return $this->ingredients;
    }

    public function setIngredients(array $ingredients): self
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getInstructions(): array
    {
        return $this->instructions;
    }

    public function setInstructions(array $instructions): self
    {
        $this->instructions = $instructions;

        return $this;
    }

    public function getTotalTime(): ?int
    {
        return $this->totalTime;
    }

    public function setTotalTime(int $totalTime): self
    {
        $this->totalTime = $totalTime;

        return $this;
    }

    public function getTimeAsWords(): string
    {
        if ($this->totalTime < 60) {
            return sprintf('%d minutes', $this->totalTime);
        }

        $hours = floor($this->totalTime / 60);
        // it's always a good day when you can use the modulo operator!
        $minutes = $this->totalTime % 60;

        return sprintf(
            '%s hour%s, %s minutes',
            $hours,
            $hours == 1 ? '' : 's',
            $minutes
        );
    }

    public function getSourceUrl(): ?string
    {
        return $this->sourceUrl;
    }

    public function setSourceUrl(string $sourceUrl): self
    {
        $this->sourceUrl = $sourceUrl;

        return $this;
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Repository\RecipeRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecipeController extends AbstractController
{
    #[Route('/recipes/{page<\d+>}', name: 'app_recipes')]
    public function recipes(RecipeRepository $recipeRepository, int $page = 1): Response
    {
        $queryBuilder = $recipeRepository->createQueryBuilderOrderedByNewest();
        $adapter = new QueryAdapter($queryBuilder);
        /** @var Recipe[]|Pagerfanta $pagerfanta */
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage($adapter, $page, 4);

        return $this->render('recipes/list.html.twig', [
            'pager' => $pagerfanta,
        ]);
    }

    #[Route('/recipes/{slug}', name: 'app_recipes_show')]
    public function recipesShow(Recipe $recipe): Response
    {
        return $this->render('recipes/show.html.twig', [
            'recipe' => $recipe
        ]);
    }
}

templates/recipes/list.html.twig
{% extends nglayouts.layoutTemplate %}

{% block title %}All Recipes{% endblock %}

{% block body %}
    <div class="hero-wrapper">
        <h1>Doggone Good Recipes</h1>
        <p>Recipes your pup will love!</p>
    </div>

    <div class="container">
        <div class="recipe-list-container py-5 px-3 mt-4" style="background-color: #fdedf0; border-radius: 5px;">
            {% for recipe in pager %}
                <div class="d-flex justify-content-center">
                    <div class="text-center recipe-container recipe-list-item p-3">
                        <a href="{{ path('app_recipes_show', { slug: recipe.slug }) }}">
                            <div class="p-3 skill-img">
                                <img src="{{ asset(recipe.imageUrl) }}" width="auto" height="115" alt="{{ recipe.name }} image">
                            </div>
                            <h3 class="mt-3">{{ recipe.subText }}</h3>
                            <small>{{ recipe.timeAsWords }} (prep & cook)</small>
                        </a>
                    </div>
                </div>
            {% endfor %}

            {% if pager.hasNextPage %}
                <div class="text-center"><u class="text-center"><a href="{{ path('app_recipes', { page: pager.nextPage }) }}">Load More Recipes</a></u></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/recipes/show.html.twig
{% extends nglayouts.layoutTemplate %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block body %}
<div class="hero-wrapper">
    <h1>{{ recipe.name }}</h1>
    <p>{{ recipe.subText }}</p>
</div>

<div class="container">
    <div class="d-flex justify-content-center my-5">
        <img src="{{asset(recipe.imageUrl)}}" width="auto" height="115" alt="{{ recipe.name }} image">
    </div>


    <h3>INGREDIENTS</h3>

    <ul>
        {% for ingredient in recipe.ingredients %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </ul>

    <h3 class="mt-5">INSTRUCTIONS</h3>

    <ol>
        {% for instruction in recipe.instructions %}
            <li>{{ instruction }}</li>
        {% endfor %}
    </ol>

    <p>recipe from:
        <u><a href="{{ recipe.sourceUrl }}">{{ recipe.sourceUrl }}</a></u>
    </p>
</div>
{% endblock %}